apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-blue
  template:
    metadata:
      labels:
        app: frontend-blue
    spec:
      containers:
        - name: frontend-blue
          image: shakti827/frontend-blue
          ports:
            - containerPort: 3100

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
spec:
  selector:
    app: frontend-blue
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: NodePort
